### ISSUE TITLE
why use the circuit breaker causes the fegin null pointer？

### ISSUE THREAD

**Issue by LXJ886** [spring-cloud/spring-cloud-circuitbreaker#152]
**Describe the bug**
java.lang.NullPointerException: null
	at org.springframework.cloud.openfeign.FeignCircuitBreakerInvocationHandler.invoke(FeignCircuitBreakerInvocationHandler.java:87)
	at com.sun.proxy.$Proxy268.getFirmwareTypes(Unknown Source)

**Comment by LXJ886** [comment]
The current situation is that I have one Fegin project that I use @Enablefeignclients (value = a.Class) in a jar package for another project to use, Also, this project also has @EableFeignClients (value = B.Class), which is done twice for FeignClientsRegistrar.registerBeanDefinitions. Causes a null pointe,I don't know if it's because of the two registerBeanDefinitions
